#!/usr/bin/python
#-*- coding: utf-8 -*-

# Parser module generated by unicc from expr.py.par.
# DO NOT EDIT THIS FILE MANUALLY, IT WILL GO AWAY!


class Node(object):
	"""
	This is an AST node.
	"""

	def __init__(self, emit = None, match = None, children = None):
		self.emit = emit
		self.match = match
		self.children = children or []

	def dump(self, level=0):
		if self.emit:
			txt = "%s%s" % (level * " ", self.emit)
			if self.match and self.match != self.emit:
				txt += " (%s)" % self.match

			print(txt)
			level += 1

		for child in self.children:
			if child:
				child.dump(level)


class ParseException(Exception):
	"""
	Exception to be raised on a parse error.
	"""

	def __init__(self, row, col, txt = None):
		if isinstance(txt, list):
			expecting = txt
			txt = ("Line %d, column %d: Parse error, expecting %s" %
					(row, col, ", ".join([("%r" % symbol[0])
						for symbol in txt])))
		else:
			expecting = None

		super(ParseException, self).__init__(txt)

		self.row = row
		self.col = col
		self.expecting = expecting


class ParserToken(object):
	state = 0
	line = 0
	column = 0

	node = None

	value = None


class ParserControlBlock(object):
	def __init__(self, input):

		# Stack
		self.stack = []
		self.tos = None

		# Values
		self.ret = None

		# State
		self.act = 0
		self.idx = None
		self.lhs = None

		# Lookahead
		self.sym = -1
		self.old_sym = -1
		self.len = 0

		# Lexical analysis
		self.lexem = None
		self.next = None
		self.eof = None
		self.is_eof = None

		# Input buffering
		self.input = input
		self.buf = ""

		# Error handling
		self.error_delay = 3
		self.error_count = 0

		self.line = 1
		self.column = 1

		


class Parser(object):

	# Actions
	_ERROR = 0
	_REDUCE = 1
	_SHIFT = 2
	_SUCCESS = 4

	# Parse tables
	_symbols = (
		("&eof", "", 3, 0, 0, 1),
		("0-9", "", 1, 0, 0, 1),
		(")", "", 1, 0, 0, 1),
		("(", "", 1, 0, 0, 1),
		("/", "", 1, 0, 0, 1),
		("*", "", 1, 0, 0, 1),
		("-", "", 1, 0, 0, 1),
		("+", "", 1, 0, 0, 1),
		("\\t ", "", 1, 0, 1, 1),
		("calc'", "", 0, 0, 0, 1),
		("int'", "", 0, 0, 0, 1),
		(")'", "", 0, 0, 0, 1),
		("('", "", 0, 0, 0, 1),
		("/'", "", 0, 0, 0, 1),
		("*'", "", 0, 0, 0, 1),
		("-'", "", 0, 0, 0, 1),
		("+'", "", 0, 0, 0, 1),
		("&whitespace*", "", 0, 1, 1, 1),
		("&whitespace+", "", 0, 1, 1, 1),
		("&whitespace", "", 0, 1, 1, 1),
		("expr", "", 0, 0, 0, 1),
		("calc", "", 0, 0, 0, 1),
		("int", "", 0, 1, 0, 1)
	)
	_productions = (
		("calc : expr ~&eof", "", 2, 21),
		("expr : expr +' expr", "", 3, 20),
		("expr : expr -' expr", "", 3, 20),
		("expr : expr *' expr", "", 3, 20),
		("expr : expr /' expr", "", 3, 20),
		("expr : (' expr )'", "", 3, 20),
		("expr : int'", "", 1, 20),
		("int : '0-9'", "", 1, 22),
		("int : int '0-9'", "", 2, 22),
		("&whitespace : '\\t '", "", 1, 19),
		("&whitespace+ : &whitespace+ &whitespace", "", 2, 18),
		("&whitespace+ : &whitespace", "", 1, 18),
		("&whitespace* : &whitespace+", "", 1, 17),
		("&whitespace* : ", "", 0, 17),
		("+' : '+' &whitespace*", "", 2, 16),
		("-' : '-' &whitespace*", "", 2, 15),
		("*' : '*' &whitespace*", "", 2, 14),
		("/' : '/' &whitespace*", "", 2, 13),
		("(' : '(' &whitespace*", "", 2, 12),
		(")' : ')' &whitespace*", "", 2, 11),
		("int' : int &whitespace*", "", 2, 10),
		("calc' : &whitespace* calc", "", 2, 9)
	)
	_act = (
		((8, 3, 9), ),
		((8, 3, 9), ),
		((3, 2, 5), (1, 3, 7), ),
		((8, 3, 9), (1, 3, 8), ),
		((0, 3, 0), (7, 2, 7), (6, 2, 8), (5, 2, 9), (4, 2, 10), ),
		((8, 3, 9), ),
		((3, 2, 5), (1, 3, 7), ),
		((8, 3, 9), ),
		((8, 3, 9), ),
		((8, 3, 9), ),
		((8, 3, 9), ),
		((3, 2, 5), (1, 3, 7), ),
		((3, 2, 5), (1, 3, 7), ),
		((3, 2, 5), (1, 3, 7), ),
		((3, 2, 5), (1, 3, 7), ),
		((7, 2, 7), (6, 2, 8), (5, 2, 9), (4, 2, 10), (2, 2, 20), ),
		((5, 2, 9), (4, 2, 10), ),
		((5, 2, 9), (4, 2, 10), ),
		(),
		(),
		((8, 3, 9), )
	)
	_go = (
		((19, 3, 11), (18, 2, 1), (17, 2, 2), ),
		((19, 3, 10), ),
		((22, 2, 3), (21, 3, 21), (20, 2, 4), (12, 2, 6), (10, 3, 6), ),
		((19, 3, 11), (18, 2, 1), (17, 3, 20), ),
		((16, 2, 11), (15, 2, 12), (14, 2, 13), (13, 2, 14), ),
		((19, 3, 11), (18, 2, 1), (17, 3, 18), ),
		((22, 2, 3), (20, 2, 15), (12, 2, 6), (10, 3, 6), ),
		((19, 3, 11), (18, 2, 1), (17, 3, 14), ),
		((19, 3, 11), (18, 2, 1), (17, 3, 15), ),
		((19, 3, 11), (18, 2, 1), (17, 3, 16), ),
		((19, 3, 11), (18, 2, 1), (17, 3, 17), ),
		((22, 2, 3), (20, 2, 16), (12, 2, 6), (10, 3, 6), ),
		((22, 2, 3), (20, 2, 17), (12, 2, 6), (10, 3, 6), ),
		((22, 2, 3), (20, 2, 18), (12, 2, 6), (10, 3, 6), ),
		((22, 2, 3), (20, 2, 19), (12, 2, 6), (10, 3, 6), ),
		((16, 2, 11), (15, 2, 12), (14, 2, 13), (13, 2, 14), (11, 3, 5), ),
		((16, 2, 11), (15, 2, 12), (14, 2, 13), (13, 2, 14), ),
		((16, 2, 11), (15, 2, 12), (14, 2, 13), (13, 2, 14), ),
		((16, 2, 11), (15, 2, 12), (14, 2, 13), (13, 2, 14), ),
		((16, 2, 11), (15, 2, 12), (14, 2, 13), (13, 2, 14), ),
		((19, 3, 11), (18, 2, 1), (17, 3, 19), )
	)

	_def_prod = (13, 12, -1, 13, -1, 13, -1, 13, 13, 13, 13, -1, -1, -1, -1, -1, 1, 2, 3, 4, 13)

	# Lexical analysis
	_dfa_select = (0, 1, 2, 3, 4, 0, 2, 0, 0, 0, 0, 2, 2, 2, 2, 5, 5, 5, 5, 5, 6)
	_dfa_index = (
		(0, 5, 6, 7),
		(8, 18, 19, 20, 21, 22, 23, 24, 25),
		(26, 29, 30),
		(31, 40, 41, 42, 43, 44, 45, 46),
		(47, 52, 53, 54, 55),
		(56, 62, 63, 64, 65, 66),
		(67, 75, 76, 77, 78, 79, 80),
	)
	_dfa_chars = ((9, 9), (32, 32), (48, 57), (40, 40), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (9, 9), (32, 32), (48, 57), (47, 47), (45, 45), (43, 43), (42, 42), (41, 41), (40, 40), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (48, 57), (40, 40), (-1, -1), (-1, -1), (-1, -1), (48, 57), (47, 47), (45, 45), (43, 43), (42, 42), (41, 41), (9, 9), (32, 32), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (47, 47), (45, 45), (43, 43), (42, 42), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (47, 47), (45, 45), (43, 43), (42, 42), (41, 41), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (47, 47), (9, 9), (32, 32), (45, 45), (43, 43), (42, 42), (41, 41), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1), (-1, -1))
	_dfa_trans = (3, 3, 2, 1, -1, -1, -1, -1, 8, 8, 2, 6, 4, 3, 5, 7, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, 1, 5, 3, 2, 4, 6, 7, 7, -1, -1, -1, -1, -1, -1, -1, -1, 2, 1, 3, 4, -1, -1, -1, -1, -1, 2, 1, 3, 4, 5, -1, -1, -1, -1, -1, -1, 4, 6, 6, 2, 1, 3, 5, -1, -1, -1, -1, -1, -1, -1)
	_dfa_accept = (
		(0, 4, 2, 9),
		(0, 4, 2, 8, 7, 6, 5, 3, 9),
		(0, 2, 4),
		(0, 2, 8, 7, 6, 5, 3, 9),
		(0, 7, 5, 8, 6),
		(0, 7, 5, 8, 6, 3),
		(0, 8, 7, 6, 5, 3, 9),
	)

	# Parsing actions

	def _reduce_action_0(self, pcb):
		print("= %d" % pcb.stack[-1 - 1].value)
		return

	def _reduce_action_1(self, pcb):
		pcb.ret = pcb.stack[-1 - 2].value + pcb.stack[-1 - 0].value
		return

	def _reduce_action_2(self, pcb):
		pcb.ret = pcb.stack[-1 - 2].value - pcb.stack[-1 - 0].value
		return

	def _reduce_action_3(self, pcb):
		pcb.ret = pcb.stack[-1 - 2].value * pcb.stack[-1 - 0].value
		return

	def _reduce_action_4(self, pcb):
		pcb.ret = pcb.stack[-1 - 2].value / pcb.stack[-1 - 0].value
		return

	def _reduce_action_5(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_6(self, pcb):
		pcb.ret = pcb.stack[-1 - 0].value
		return

	def _reduce_action_7(self, pcb):
		pcb.ret = ord(pcb.stack[-1 - 0].value) - ord('0')
		return

	def _reduce_action_8(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value * 10 + ord(pcb.stack[-1 - 0].value) - ord('0')
		return

	def _reduce_action_14(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_15(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_16(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_17(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_18(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_19(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_20(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return

	def _reduce_action_21(self, pcb):
		pcb.ret = pcb.stack[-1 - 1].value
		return



	# Parsing algorithm

	def _get_act(self, pcb):
		# Get action table entry

		# Check action table first
		for (sym, pcb.act, pcb.idx) in self._act[pcb.tos.state]:
			if sym == pcb.sym:
				return True if pcb.act else False #enforced parse error

		# Otherwise, apply default production
		pcb.idx = self._def_prod[pcb.tos.state]
		if pcb.idx > -1:
			pcb.act = self._REDUCE
			return True

		return False

	def _get_go(self, pcb):
		# Get goto table entry

		for (sym, pcb.act, pcb.idx) in self._go[pcb.tos.state]:
			if sym == pcb.lhs:
				return True

		return False

	def _get_char(self, pcb):
		# Get next character from input stream

		if callable(pcb.input):
			return pcb.input()

		if pcb.input:
			ch = pcb.input[0]
			pcb.input = pcb.input[1:]
		else:
			ch = pcb.eof

		return ch

	def _get_input(self, pcb, offset):
		# Performs input buffering

		while offset >= len(pcb.buf):
			if pcb.is_eof:
				return pcb.eof

			ch = self._get_char(pcb)
			if ch == pcb.eof:
				pcb.is_eof = True
				return pcb.eof

			pcb.buf += ch

		#print("_get_input", pcb.buf, offset, pcb.buf[offset], ord(pcb.buf[offset]))

		return ord(pcb.buf[offset])

	def _clear_input(self, pcb):
		# Purge input from buffer that is not necessary anymore

		if pcb.buf:

			# Perform position counting.
			for ch in pcb.buf[0: pcb.len]:
				if ch == '\n':
					pcb.line += 1
					pcb.column = 0
				else:
					pcb.column += 1

			pcb.buf = pcb.buf[pcb.len:]

		pcb.len = 0
		pcb.sym = -1

	def _lex(self, pcb):
		# Lexical analysis

		state = length = 0
		machine = self._dfa_select[pcb.tos.state] if not 0 else 0
		next = self._get_input(pcb, length)

		if next == pcb.eof:
			pcb.sym = 0
			return

		while state > -1 and next != pcb.eof:
			idx = self._dfa_index[machine][state]
			state = -1

			while self._dfa_chars[idx][0] > -1:
				if (next >= self._dfa_chars[idx][0]
					and next <= self._dfa_chars[idx][1]):

					length += 1
					state = self._dfa_trans[idx]

					if self._dfa_accept[machine][state] > 0:
						pcb.sym = self._dfa_accept[machine][state] - 1
						pcb.len = length

						# Test! (??)
						if pcb.sym == 0:
							state = -1
							break

						# Stop if matched symbol should be parsed nongreedy
						if not self._symbols[pcb.sym][5]:
							state = -1
							break

					next = self._get_input(pcb, length)
					break

				idx += 1

			# TODO: Semantic Terminal Selection?

		#print("_lex", pcb.sym, pcb.len)

	def _get_sym(self, pcb):
		# Get lookahead symbol

		pcb.sym = -1
		pcb.len = 0

		# insensitive mode
		if 0:
			while True:
				self._lex(pcb)

				# check for whitespace
				if pcb.sym > -1 and self._symbols[pcb.sym][4]:
					self._clear_input(pcb)
					continue

				break

		# sensitive mode
		else:
			if self._dfa_select[pcb.tos.state] > -1:
				self._lex(pcb)

			# If there is no matching DFA state machine, try to identify the
			# end-of-file symbol. If this also fails, a parse error will raise.
			elif self._get_input(pcb, 0) == pcb.eof:
				pcb.sym = 0

		return pcb.sym > -1

	def parse(self, s = None):
		if s is None:
			try:
				s = raw_input(">")
			except NameError:
				s = input(">")

		pcb = ParserControlBlock(s)
		pcb.act = self._SHIFT

		pcb.tos = ParserToken()
		pcb.stack.append(pcb.tos)

		while True:
			#print("state = %d" % pcb.tos.state)

			# Reduce
			while pcb.act & self._REDUCE:

				# Set default left-hand side
				pcb.lhs = self._productions[pcb.idx][3]

				#print("REDUCE", pcb.idx, self._productions[pcb.idx][0])
				#print("state", pcb.tos.state)

				# Call reduce function
				#print("CALL", "_reduce_action_%d" % pcb.idx)
				reduce_fn = getattr(self, "_reduce_action_%d" % pcb.idx, None)
				if reduce_fn:
					reduce_fn(pcb)

				# Drop right-hand side
				cnodes = None
				for _ in range(0, self._productions[pcb.idx][2]):
					item = pcb.stack.pop()

					if item.node:
						if cnodes is None:
							cnodes = []

						if isinstance(item.node, list):
							cnodes = item.node + cnodes
						else:
							cnodes.insert(0, item.node)

				pcb.tos = pcb.stack[-1]
				pcb.tos.value = pcb.ret

				# Handle AST nodes
				if self._productions[pcb.idx][1]:
					#print("%s = %s" % (self._productions[pcb.idx][0], self._productions[pcb.idx][1]))
					node = Node(self._productions[pcb.idx][1],
											children=cnodes)

				else:
					node = None

				# Error enforced by semantics?
				if pcb.act == self._ERROR:
					break

				# Goal symbol reduced, and stack is empty?
				if pcb.lhs == 9 and len(pcb.stack) == 1:
					pcb.tos.node = node or cnodes
					self._clear_input(pcb)
					pcb.act = self._SUCCESS;
					break

				self._get_go(pcb)

				pcb.tos = ParserToken()
				pcb.stack.append(pcb.tos)

				pcb.tos.symbol = self._symbols[pcb.lhs]
				pcb.tos.state = -1 if pcb.act & self._REDUCE else pcb.idx
				pcb.tos.value = pcb.ret
				pcb.tos.node = node or cnodes
				pcb.tos.line = pcb.line
				pcb.tos.column = pcb.column

			if pcb.act == self._SUCCESS or pcb.act == self._ERROR:
				break

			# Get next input symbol
			self._get_sym(pcb)

			#print("pcb.sym = %d (%s)" % (pcb.sym, self._symbols[pcb.sym][0]))
			#print("pcb.len = %d" % pcb.len)

			# Get action table entry
			if not self._get_act(pcb):
				# TODO: Error Recovery
				raise ParseException(pcb.line, pcb.column,
					[self._symbols[sym]
						for (sym, pcb.act, pcb.idx)
							in self._act[pcb.tos.state]])

			#print("pcb.act = %d" % pcb.act)

			# Shift
			if pcb.act & self._SHIFT:
				#print("SHIFT", pcb.sym, self._symbols[pcb.sym])

				pcb.tos = ParserToken()
				pcb.stack.append(pcb.tos)

				# Execute scanner actions, if existing.
				scan_fn = getattr(self, "_scan_action_%d" % pcb.sym, None)
				if scan_fn:
					scan_fn(pcb)

				pcb.tos.state = -1 if pcb.act & self._REDUCE else pcb.idx
				pcb.tos.symbol = self._symbols[pcb.sym]

				pcb.tos.line = pcb.line
				pcb.tos.column = pcb.column
				pcb.stack[-1 - 0].value = pcb.buf[:pcb.len]

				if pcb.tos.symbol[1]:
					pcb.tos.node = Node(pcb.tos.symbol[1], pcb.stack[-1 - 0].value)

				if pcb.sym != 0 and pcb.sym != -1:
					self._clear_input(pcb)
					pcb.old_sym = -1

		if pcb.ret is None and pcb.tos.node:
			if isinstance(pcb.tos.node, list):
				if len(pcb.tos.node) > 1:
					node = Node(children=pcb.tos.node)
				else:
					node = pcb.tos.node[0]
			else:
				node = pcb.tos.node
		else:
			node = None

		return pcb.ret or node



if __name__ == "__main__":
	import sys

	p = Parser()
	ret = p.parse(sys.argv[1] if len(sys.argv) > 1 else None)

	if isinstance(ret, Node):
		ret.dump()
	else:
		print(ret)

